### ISSUE TITLE
keymap: dedicate keybindings for parent/first-child

### ISSUE THREAD

**Issue by wongjiahau** [ki-editor/ki-editor#339]
# Problem
Currently, the behavior of `j`/`k` in Syntax Node selection mode is surprising, as it doesn't mean "move to the sibling node of the line below/above". 

# Proposed changes
1. Change `x` (Enter exchange mode) to mean Expand selection (Parent node) and enter Syntax Node (Coarse) selection mode at the same time
2. Change `z` (Column selection mode) to mean Shrink selection (First-child) and enter Syntax Node (Coarse) selection mode at the same time
3. Assign `alt+<movement>` to mean exchange-movement:
    - `alt+h` exchange current selection with previous selection
    - `alt+l` exchange current selection with next selection
    - `alt+j` exchange current selection with nearest selection below
    - `alt+k` exchange current selection with nearest selection above
    - `alt+f` exchange current selection with a distant selection
4. Assign `^` (Raise)/`$` (unbounded) to mean enter column selection mode at the beginning/end of current selection
5. Assign `alt+x` to mean Raise

**Comment by jbhoot** [comment]
To me, the repercussions on exchange and column selection outweigh the benefits of freeing `z` and `x` for parent/first-child in syntax node selection mode.

I think your logic for current keybindings was to have the selection mode keys on LHS, movement keys on RHS, so that user can switch between modes without having to move away from `hjkl`.

That's a good approach. We should stick to it.

I quickly checked unbound keys. I got `r`, `n`, `'`. Also, `[` and `]` seem to do the same thing.

May be we can do something around those? I am throwing a few ideas in the ring before I go off to work:

1. The syntax selection mode is different from the other modes in that the size of its "unit" is variable, and can be reduced or expanded. So there is no harm in having two keys which can switch to syntax selection mode. With this in mind, use `s` and `r`, where both of them switches to selection mode, and `s` *swells* the selection, and `r` *reduces* the selection. Or we can swap depending on which mnemonic you can find. This is similar to your `z` and `x` proposal.
2. Keep `s` to switch to selection mode, and dedicate two other keys to expand/shrink selection such that `hjkl` movements are only a finger away. Along those lines, we could:
  a. use `;` and `'`. The latter looks unused to me, while we could re-assign the replace function of `;` to the seemingly unused `r`.
  b. `n` looks unused too. We could use `n` and `m`, while we re-assing the mark function of `m` to `'`. If you squint, `'` can be related to mark function as marking something with quotes or something.
  c. I had half a mind to recommend `i` (select inwards) and `o` (select outwards), where we can re-assign `o`'s function to `n` (new line or new node). But `i` for insert is non-negotiable. Also, re-assigning `o` would be incompatible to vim, which you don't seem to want to do.

Or you may figure out some other permutation of the above after adjusting current keybindings, given you have much better experience than I have.

**Comment by jbhoot** [comment]
Out of my suggestions, `s` and `r`; or `m` and `n` look the most ergonomic to me.

**Comment by wongjiahau** [comment]
> To me, the repercussions on exchange and column selection outweigh the benefits of freeing z and x for parent/first-child in syntax node selection mode.

Yup `z` seems too important to be rebound, but just out of curiosity, do you use `x` a lot?

> I think your logic for current keybindings was to have the selection mode keys on LHS, movement keys on RHS, so that user can switch between modes without having to move away from hjkl.

It was unintended actually, but it made sense once you mentioned it.


> I quickly checked unbound keys. I got r, n, '. Also, [ and ] seem to do the same thing.

`r` is bound to `Replace`, which is super useful (it behaves like Vim's Paste), so we can't rebind `r`.
`n` is also bound to "Set to last non-contiguous selection mode".

`'` is indeed unbound.

> ... `m` and `n` look the most ergonomic to me.

I don't wish to rebind these because I use them a lot 🥲.



Anyway those are good ideas, and they sparked something in my mind. How about this? 

1. Change `z` to `'` (roughly means character, since most system programming languages use single quotes for character literal)
2. Change `x` to `alt+<movement>`
3. Bind `z`/`x` to shrink/e**x**pand

**Comment by jbhoot** [comment]
`x` in Ki is so ergonomic to exchange units that I have used it a lot of times in the past couple of days. I never even looked up keybindings for it in helix or (n)vim plugins.

I would be loathe to lose it, but if you really want to go in that direction, we could experiment with it in a separate branch or something.

Other ideas that came to me that could retain `x`:

1. Use `s` and `'` to set syntax selection mode as well as swell or reduce the selection. While `s` and `'` are apart, they fit perfectly in an ergonomic sense without having to move either of hands. This also retains `z`, which keeps all selection modes to LHS – not a non-negotiable but is surely neat. To make things even better, rebind replace function of `;` to `'`, and use `;` to reduce selection.
2. Move only the function of `z` to `'` like you suggested. Use `s` and `z` to set selection mode and swell or reduce selection.

I think 1 (`s` and `;`) is more ergonomic than 2 (`s` and `z`).

**Comment by wongjiahau** [comment]
> `x` in Ki is so ergonomic to exchange units that I have used it a lot of times in the past couple of days. For example, I used it in Ki's languages.rs to re-order extensions. In contrast, I never even looked up keybindings for it in helix or (n)vim plugins.

Understandable, it looks like we have to keep `x` untouched then.

> Use `s` and `'` to set syntax selection mode as well as swell or reduce the selection.

`s` cannot be rebound to mean expand/swell because besides setting the selection mode to syntax node, it also selects the largest node, which is one of Ki's killer feature IMHO. 

Now that I think about it, I thought one of your previous suggestions of using `;`/`'` to mean first-child/parent made sense. What do you think? 

P/S: I almost never use `;` (replace mode) to be honest, I created it because it fulfills my desire to invent grand abstractions.

**Comment by jbhoot** [comment]
> P/S: I almost never use ; (replace mode) to be honest, I created it because it fulfills my desire to invent grand abstractions.

😅 I haven't found a usecase of it either.

> Now that I think about it, I thought one of your previous suggestions of using ;/' to mean first-child/parent made sense. What do you think?

We can try it out.

̛If you go through with this, are all the keys bound already? I think only `~` and `=` are unbound?

Should there be a key left unbound to enable two-key bindings, similar to what vim does with `g`, or users use leader key for in vim? We can never predict every use case right away.

**Comment by wongjiahau** [comment]
> We can try it out.

Do you want to give it a try and see how it feels?

**Comment by wongjiahau** [comment]
> ̛If you go through with this, are all the keys bound already? I think only ~ and = are unbound?

IIRC @, *, # are also unbound. 

Note: @ should be changed to `space ?`

**Comment by jbhoot** [comment]
> Doesn’t space cover this use case already? Or were you referring to something else?

Right, space should work.

**Comment by jbhoot** [comment]
> Do you want to give it a try and see how it feels?

As in, change the code? Sure, I can try it out. I need to learn Rust first, though. I was able to edit `languages.rs` because Rust shares lots of principles with OCaml. Before I dive deep in the main code, though, I should at least work though the official tutorial.

**Comment by wongjiahau** [comment]
> As in, change the code?
 
Yup.

> Sure, I can try it out.

Great! IIRC you only need to change the content in `editor_keymap_legened.rs` to get it going.

> I need to learn Rust first, though. I was able to edit languages.rs because Rust shares lots of principles with OCaml.

No worries, Rust was bootstrapped with OCaml, so Rust sure feels reminiscent of OCaml, ignoring the syntax, the most notable difference is only the borrow checker, and I don't mind flex-taping `.clone()`s here and there to satisfy the borrow checker.

> Before I dive deep in the main code, though, I should at least work though the official tutorial.

No worries, take your time. 🧠

**Comment by wongjiahau** [comment]
I came to a realization when I was thinking about this:
1. `;`/`'` are not easy to use because the imprecise right pinky controls both, thus prone to mistakes.
2. `n` is not as common as I thought; it can be remapped to something else like `;` (also quite Vim-esque, as `;` means "repeat the last f/t movement". In Ki's case, it means "repeat the last non-contiguous movement").
3. The commands buried under `b` can be nested under `v`, which makes Ki even more Vim-compatible, so `bi(` becomes `vi(` and etc., with extra actions like `vd` (delete surround), `vs` (surround), and `vc` (change surround).
4. This leaves us with `b` and `n`. Mnemonic-wise, `b` for "bigger" and `n` for "narrower" is very sensible; while keyboard layout-wise it should be reversed, since `n` is located to the right of `b`.

What do you think?

**Comment by jbhoot** [comment]
> ;/' are not easy to use because the imprecise right pinky controls both, thus prone to mistakes.

I was going to mention the same today 😅 Reduces accuracy and increases pain. It will be Ki's own version of Emacs Pinky.

> n is not as common as I thought;

That's why I recommended `m` and `n` yesterday. But I agree `m` is better used for mark function.

I agree with the rest of the points. `b` and `n` are excellent, ergonomic bindings for *bigger* and *narrower* selections.

**Comment by wongjiahau** [comment]
Great! Since its scope is considerably large, do you mind if I work on it instead?

**Comment by jbhoot** [comment]
Of course! I have no experience with the codebase. Please go ahead.

**Comment by wongjiahau** [comment]
@jbhoot Since `t` will be removed in #342, what do you think of the following keybindings instead `b`/`n`?
- `t`: Top, meaning Parent, in the top row of QWERTY
- `b`: Bottom, meaning First child, in the bottom row of QWERTY
